export const USER_FETCH_TOKENS = 'USER_FETCH_TOKENS'

export const USER_FETCH_TOKEN = 'USER_FETCH_TOKEN'
export const USER_FETCH_REFRESH_TOKEN = 'USER_FETCH_REFRESH_TOKEN';
export const USER_FETCH_BALANCE = 'USER_FETCH_BALANCE'
export const USER_FETCH_GAMES = 'USER_FETCH_GAMES'
export const USER_FETCH_GAME = 'USER_FETCH_GAME'

export const USER_IS_LOGGED = 'USER_IS_LOGGED'

export const USER_LOADING_START = 'USER_LOADING_START'
export const USER_LOADING_FINISH = 'USER_LOADING_FINISH'

export const USER_SET_IS_COME_FROM_LOGIN = 'USER_SET_IS_COME_FROM_LOGIN'
export const USER_SET_IS_AUTH = 'USER_SET_IS_AUTH'

export const USER_LOG_OUT = 'USER_LOG_OUT'








